// my_eth_eth_tse_0_altera_eth_tse_1930_3dm6xba.v

// This file was auto-generated from altera_eth_tse_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.3 222

`timescale 1 ps / 1 ps
module my_eth_eth_tse_0_altera_eth_tse_1930_3dm6xba (
		input  wire        ff_tx_clk,      //     transmit_clock_connection.clk
		input  wire        ff_rx_clk,      //      receive_clock_connection.clk
		output wire [31:0] ff_rx_data,     //                       receive.data
		output wire        ff_rx_eop,      //                              .endofpacket
		output wire [5:0]  rx_err,         //                              .error
		output wire [1:0]  ff_rx_mod,      //                              .empty
		input  wire        ff_rx_rdy,      //                              .ready
		output wire        ff_rx_sop,      //                              .startofpacket
		output wire        ff_rx_dval,     //                              .valid
		input  wire [31:0] ff_tx_data,     //                      transmit.data
		input  wire        ff_tx_eop,      //                              .endofpacket
		input  wire        ff_tx_err,      //                              .error
		input  wire [1:0]  ff_tx_mod,      //                              .empty
		output wire        ff_tx_rdy,      //                              .ready
		input  wire        ff_tx_sop,      //                              .startofpacket
		input  wire        ff_tx_wren,     //                              .valid
		input  wire        xon_gen,        //           mac_misc_connection.xon_gen
		input  wire        xoff_gen,       //                              .xoff_gen
		input  wire        ff_tx_crc_fwd,  //                              .ff_tx_crc_fwd
		output wire        ff_tx_septy,    //                              .ff_tx_septy
		output wire        tx_ff_uflow,    //                              .tx_ff_uflow
		output wire        ff_tx_a_full,   //                              .ff_tx_a_full
		output wire        ff_tx_a_empty,  //                              .ff_tx_a_empty
		output wire [17:0] rx_err_stat,    //                              .rx_err_stat
		output wire [3:0]  rx_frm_type,    //                              .rx_frm_type
		output wire        ff_rx_dsav,     //                              .ff_rx_dsav
		output wire        ff_rx_a_full,   //                              .ff_rx_a_full
		output wire        ff_rx_a_empty,  //                              .ff_rx_a_empty
		input  wire        clk,            // control_port_clock_connection.clk
		input  wire        reset,          //              reset_connection.reset
		output wire [31:0] reg_data_out,   //                  control_port.readdata
		input  wire        reg_rd,         //                              .read
		input  wire [31:0] reg_data_in,    //                              .writedata
		input  wire        reg_wr,         //                              .write
		output wire        reg_busy,       //                              .waitrequest
		input  wire [7:0]  reg_addr,       //                              .address
		input  wire        ref_clk,        //  pcs_ref_clk_clock_connection.clk
		output wire        led_crs,        //         status_led_connection.crs
		output wire        led_link,       //                              .link
		output wire        led_panel_link, //                              .panel_link
		output wire        led_col,        //                              .col
		output wire        led_an,         //                              .an
		output wire        led_char_err,   //                              .char_err
		output wire        led_disp_err,   //                              .disp_err
		output wire        rx_recovclkout, //     serdes_control_connection.export
		input  wire        rxp,            //             serial_connection.rxp_0
		output wire        txp             //                              .txp_0
	);

	wire  [31:0] avalon_arbiter_av_mac_master_0_readdata;                               // i_tse_mac:reg_data_out -> avalon_arbiter:mac_readdata_0
	wire         avalon_arbiter_av_mac_master_0_waitrequest;                            // i_tse_mac:reg_busy -> avalon_arbiter:mac_waitrequest_0
	wire   [7:0] avalon_arbiter_av_mac_master_0_address;                                // avalon_arbiter:mac_address_0 -> i_tse_mac:reg_addr
	wire         avalon_arbiter_av_mac_master_0_read;                                   // avalon_arbiter:mac_read_0 -> i_tse_mac:reg_rd
	wire  [31:0] avalon_arbiter_av_mac_master_0_writedata;                              // avalon_arbiter:mac_writedata_0 -> i_tse_mac:reg_data_in
	wire         avalon_arbiter_av_mac_master_0_write;                                  // avalon_arbiter:mac_write_0 -> i_tse_mac:reg_wr
	wire         i_lvdsio_terminator_0_lvds_rx_inclock_export;                          // i_lvdsio_terminator_0:lvds_rx_inclock -> i_lvdsio_rx_0:inclock
	wire   [9:0] i_lvdsio_rx_0_rx_out_export;                                           // i_lvdsio_rx_0:rx_out -> i_lvdsio_terminator_0:rx_out
	wire   [0:0] i_lvdsio_terminator_0_rx_in_export;                                    // i_lvdsio_terminator_0:rx_in -> i_lvdsio_rx_0:rx_in
	wire   [0:0] i_lvdsio_terminator_0_rx_dpa_reset_export;                             // i_lvdsio_terminator_0:rx_dpa_reset -> i_lvdsio_rx_0:rx_dpa_reset
	wire   [0:0] i_lvdsio_rx_0_rx_dpa_locked_export;                                    // i_lvdsio_rx_0:rx_dpa_locked -> i_lvdsio_terminator_0:rx_dpa_locked
	wire   [0:0] i_lvdsio_rx_0_rx_divfwdclk_export;                                     // i_lvdsio_rx_0:rx_divfwdclk -> i_lvdsio_terminator_0:rx_divfwdclk
	wire         i_lvdsio_rx_0_rx_coreclock_export;                                     // i_lvdsio_rx_0:rx_coreclock -> i_lvdsio_terminator_0:rx_coreclock
	wire         i_lvdsio_rx_0_pll_locked_export;                                       // i_lvdsio_rx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_rx
	wire         i_lvdsio_terminator_0_pll_areset_rx_export;                            // i_lvdsio_terminator_0:pll_areset_rx -> i_lvdsio_rx_0:pll_areset
	wire         i_lvdsio_terminator_0_lvds_tx_inclock_export;                          // i_lvdsio_terminator_0:lvds_tx_inclock -> i_lvdsio_tx_0:inclock
	wire   [9:0] i_lvdsio_terminator_0_tx_in_export;                                    // i_lvdsio_terminator_0:tx_in -> i_lvdsio_tx_0:tx_in
	wire   [0:0] i_lvdsio_tx_0_tx_out_export;                                           // i_lvdsio_tx_0:tx_out -> i_lvdsio_terminator_0:tx_out
	wire         i_lvdsio_tx_0_pll_locked_export;                                       // i_lvdsio_tx_0:pll_locked -> i_lvdsio_terminator_0:pll_locked_tx
	wire         i_lvdsio_terminator_0_pll_areset_tx_export;                            // i_lvdsio_terminator_0:pll_areset_tx -> i_lvdsio_tx_0:pll_areset
	wire   [9:0] i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed;                             // i_tse_pcs_0:tbi_tx_d_muxed -> i_lvdsio_terminator_0:tbi_tx_d_muxed_0
	wire   [9:0] i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds;                   // i_lvdsio_terminator_0:tbi_rx_d_lvds_0 -> i_tse_pcs_0:tbi_rx_d_lvds
	wire         i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk;                         // i_lvdsio_terminator_0:tbi_rx_clk_0 -> i_tse_pcs_0:tbi_rx_clk
	wire         i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done; // i_lvdsio_terminator_0:rx_reset_sequence_done_0 -> i_tse_pcs_0:rx_reset_sequence_done
	wire         i_lvdsio_terminator_0_rx_reset_0_rx_reset;                             // i_lvdsio_terminator_0:rx_reset_0 -> i_tse_pcs_0:rx_reset
	wire         i_lvdsio_terminator_0_tx_reset_0_tx_reset;                             // i_lvdsio_terminator_0:tx_reset_0 -> i_tse_pcs_0:tx_reset
	wire  [15:0] avalon_arbiter_av_pcs_master_0_readdata;                               // i_tse_pcs_0:reg_data_out -> avalon_arbiter:pcs_readdata_0
	wire         avalon_arbiter_av_pcs_master_0_waitrequest;                            // i_tse_pcs_0:reg_busy -> avalon_arbiter:pcs_waitrequest_0
	wire   [4:0] avalon_arbiter_av_pcs_master_0_address;                                // avalon_arbiter:pcs_address_0 -> i_tse_pcs_0:reg_addr
	wire         avalon_arbiter_av_pcs_master_0_read;                                   // avalon_arbiter:pcs_read_0 -> i_tse_pcs_0:reg_rd
	wire  [15:0] avalon_arbiter_av_pcs_master_0_writedata;                              // avalon_arbiter:pcs_writedata_0 -> i_tse_pcs_0:reg_data_in
	wire         avalon_arbiter_av_pcs_master_0_write;                                  // avalon_arbiter:pcs_write_0 -> i_tse_pcs_0:reg_wr
	wire         i_tse_pcs_0_pcs_transmit_clock_connection_clk;                         // i_tse_pcs_0:tx_clk -> [i_tse_mac:tx_clk, rst_controller:clk]
	wire         i_tse_pcs_0_pcs_receive_clock_connection_clk;                          // i_tse_pcs_0:rx_clk -> [i_tse_mac:rx_clk, rst_controller_001:clk]
	wire   [7:0] i_tse_pcs_0_gmii_connection_gmii_rx_d;                                 // i_tse_pcs_0:gmii_rx_d -> i_tse_mac:gm_rx_d
	wire         i_tse_pcs_0_gmii_connection_gmii_rx_err;                               // i_tse_pcs_0:gmii_rx_err -> i_tse_mac:gm_rx_err
	wire         i_tse_pcs_0_gmii_connection_gmii_rx_dv;                                // i_tse_pcs_0:gmii_rx_dv -> i_tse_mac:gm_rx_dv
	wire   [7:0] i_tse_mac_mac_gmii_connection_gmii_tx_d;                               // i_tse_mac:gm_tx_d -> i_tse_pcs_0:gmii_tx_d
	wire         i_tse_mac_mac_gmii_connection_gmii_tx_en;                              // i_tse_mac:gm_tx_en -> i_tse_pcs_0:gmii_tx_en
	wire         i_tse_mac_mac_gmii_connection_gmii_tx_err;                             // i_tse_mac:gm_tx_err -> i_tse_pcs_0:gmii_tx_err
	wire         i_tse_mac_mac_mii_connection_mii_tx_en;                                // i_tse_mac:m_tx_en -> i_tse_pcs_0:mii_tx_en
	wire   [3:0] i_tse_pcs_0_mii_connection_mii_rx_d;                                   // i_tse_pcs_0:mii_rx_d -> i_tse_mac:m_rx_d
	wire         i_tse_pcs_0_mii_connection_mii_col;                                    // i_tse_pcs_0:mii_col -> i_tse_mac:m_rx_col
	wire   [3:0] i_tse_mac_mac_mii_connection_mii_tx_d;                                 // i_tse_mac:m_tx_d -> i_tse_pcs_0:mii_tx_d
	wire         i_tse_mac_mac_mii_connection_mii_tx_err;                               // i_tse_mac:m_tx_err -> i_tse_pcs_0:mii_tx_err
	wire         i_tse_pcs_0_mii_connection_mii_crs;                                    // i_tse_pcs_0:mii_crs -> i_tse_mac:m_rx_crs
	wire         i_tse_pcs_0_mii_connection_mii_rx_err;                                 // i_tse_pcs_0:mii_rx_err -> i_tse_mac:m_rx_err
	wire         i_tse_pcs_0_mii_connection_mii_rx_dv;                                  // i_tse_pcs_0:mii_rx_dv -> i_tse_mac:m_rx_en
	wire         i_tse_pcs_0_sgmii_status_connection_set_1000;                          // i_tse_pcs_0:set_1000 -> i_tse_mac:set_1000
	wire         i_tse_pcs_0_sgmii_status_connection_set_10;                            // i_tse_pcs_0:set_10 -> i_tse_mac:set_10
	wire         i_tse_pcs_0_clock_enable_connection_tx_clkena;                         // i_tse_pcs_0:tx_clkena -> i_tse_mac:tx_clkena
	wire         i_tse_pcs_0_clock_enable_connection_rx_clkena;                         // i_tse_pcs_0:rx_clkena -> i_tse_mac:rx_clkena
	wire         rst_controller_reset_out_reset;                                        // rst_controller:reset_out -> i_tse_pcs_0:reset_tx_clk
	wire         rst_controller_001_reset_out_reset;                                    // rst_controller_001:reset_out -> i_tse_pcs_0:reset_rx_clk

	altera_eth_tse_mac #(
		.ING_ADDR                 (11),
		.ENABLE_MAC_RX_VLAN       (0),
		.ENABLE_SUP_ADDR          (0),
		.DEVICE_FAMILY            ("ARRIA10"),
		.INSERT_TA                (0),
		.ING_FIFO                 (2048),
		.ENABLE_ECC               (0),
		.CRC32DWIDTH              (8),
		.ENABLE_ENA               (32),
		.SYNCHRONIZER_DEPTH       (3),
		.ENABLE_MAC_TX_VLAN       (0),
		.RESET_LEVEL              (1),
		.STAT_CNT_ENA             (1),
		.CUST_VERSION             (0),
		.CRC32S1L2_EXTERN         (0),
		.MBIT_ONLY                (1),
		.EG_ADDR                  (11),
		.CORE_VERSION             (4867),
		.CRC32GENDELAY            (6),
		.EG_FIFO                  (2048),
		.REDUCED_INTERFACE_ENA    (0),
		.ENABLE_MAGIC_DETECT      (0),
		.ENABLE_MDIO              (0),
		.ENABLE_MAC_TXADDR_SET    (1),
		.RAM_TYPE                 ("AUTO"),
		.CRC32CHECK16BIT          (0),
		.ENABLE_LGTH_CHECK        (1),
		.ENABLE_MAC_FLOW_CTRL     (1),
		.ENABLE_SHIFT16           (1),
		.USE_SYNC_RESET           (1),
		.REDUCED_CONTROL          (0),
		.MDIO_CLK_DIV             (50),
		.ENABLE_PADDING           (1),
		.ENABLE_GMII_LOOPBACK     (0),
		.GBIT_ONLY                (1),
		.ENA_HASH                 (0),
		.ENABLE_EXTENDED_STAT_REG (0),
		.ENABLE_HD_LOGIC          (0)
	) i_tse_mac (
		.clk             (clk),                                           //   input,   width = 1, control_port_clock_connection.clk
		.reset           (reset),                                         //   input,   width = 1,              reset_connection.reset
		.reg_addr        (avalon_arbiter_av_mac_master_0_address),        //   input,   width = 8,                  control_port.address
		.reg_data_out    (avalon_arbiter_av_mac_master_0_readdata),       //  output,  width = 32,                              .readdata
		.reg_rd          (avalon_arbiter_av_mac_master_0_read),           //   input,   width = 1,                              .read
		.reg_data_in     (avalon_arbiter_av_mac_master_0_writedata),      //   input,  width = 32,                              .writedata
		.reg_wr          (avalon_arbiter_av_mac_master_0_write),          //   input,   width = 1,                              .write
		.reg_busy        (avalon_arbiter_av_mac_master_0_waitrequest),    //  output,   width = 1,                              .waitrequest
		.ff_tx_clk       (ff_tx_clk),                                     //   input,   width = 1,     transmit_clock_connection.clk
		.ff_rx_clk       (ff_rx_clk),                                     //   input,   width = 1,      receive_clock_connection.clk
		.ff_rx_data      (ff_rx_data),                                    //  output,  width = 32,                       receive.data
		.ff_rx_eop       (ff_rx_eop),                                     //  output,   width = 1,                              .endofpacket
		.rx_err          (rx_err),                                        //  output,   width = 6,                              .error
		.ff_rx_mod       (ff_rx_mod),                                     //  output,   width = 2,                              .empty
		.ff_rx_rdy       (ff_rx_rdy),                                     //   input,   width = 1,                              .ready
		.ff_rx_sop       (ff_rx_sop),                                     //  output,   width = 1,                              .startofpacket
		.ff_rx_dval      (ff_rx_dval),                                    //  output,   width = 1,                              .valid
		.ff_tx_data      (ff_tx_data),                                    //   input,  width = 32,                      transmit.data
		.ff_tx_eop       (ff_tx_eop),                                     //   input,   width = 1,                              .endofpacket
		.ff_tx_err       (ff_tx_err),                                     //   input,   width = 1,                              .error
		.ff_tx_mod       (ff_tx_mod),                                     //   input,   width = 2,                              .empty
		.ff_tx_rdy       (ff_tx_rdy),                                     //  output,   width = 1,                              .ready
		.ff_tx_sop       (ff_tx_sop),                                     //   input,   width = 1,                              .startofpacket
		.ff_tx_wren      (ff_tx_wren),                                    //   input,   width = 1,                              .valid
		.xon_gen         (xon_gen),                                       //   input,   width = 1,           mac_misc_connection.export
		.xoff_gen        (xoff_gen),                                      //   input,   width = 1,                              .export
		.ff_tx_crc_fwd   (ff_tx_crc_fwd),                                 //   input,   width = 1,                              .export
		.ff_tx_septy     (ff_tx_septy),                                   //  output,   width = 1,                              .export
		.tx_ff_uflow     (tx_ff_uflow),                                   //  output,   width = 1,                              .export
		.ff_tx_a_full    (ff_tx_a_full),                                  //  output,   width = 1,                              .export
		.ff_tx_a_empty   (ff_tx_a_empty),                                 //  output,   width = 1,                              .export
		.rx_err_stat     (rx_err_stat),                                   //  output,  width = 18,                              .export
		.rx_frm_type     (rx_frm_type),                                   //  output,   width = 4,                              .export
		.ff_rx_dsav      (ff_rx_dsav),                                    //  output,   width = 1,                              .export
		.ff_rx_a_full    (ff_rx_a_full),                                  //  output,   width = 1,                              .export
		.ff_rx_a_empty   (ff_rx_a_empty),                                 //  output,   width = 1,                              .export
		.gm_rx_d         (i_tse_pcs_0_gmii_connection_gmii_rx_d),         //   input,   width = 8,           mac_gmii_connection.gmii_rx_d
		.gm_rx_dv        (i_tse_pcs_0_gmii_connection_gmii_rx_dv),        //   input,   width = 1,                              .gmii_rx_dv
		.gm_rx_err       (i_tse_pcs_0_gmii_connection_gmii_rx_err),       //   input,   width = 1,                              .gmii_rx_err
		.gm_tx_d         (i_tse_mac_mac_gmii_connection_gmii_tx_d),       //  output,   width = 8,                              .gmii_tx_d
		.gm_tx_en        (i_tse_mac_mac_gmii_connection_gmii_tx_en),      //  output,   width = 1,                              .gmii_tx_en
		.gm_tx_err       (i_tse_mac_mac_gmii_connection_gmii_tx_err),     //  output,   width = 1,                              .gmii_tx_err
		.m_rx_d          (i_tse_pcs_0_mii_connection_mii_rx_d),           //   input,   width = 4,            mac_mii_connection.mii_rx_d
		.m_rx_en         (i_tse_pcs_0_mii_connection_mii_rx_dv),          //   input,   width = 1,                              .mii_rx_dv
		.m_rx_err        (i_tse_pcs_0_mii_connection_mii_rx_err),         //   input,   width = 1,                              .mii_rx_err
		.m_tx_d          (i_tse_mac_mac_mii_connection_mii_tx_d),         //  output,   width = 4,                              .mii_tx_d
		.m_tx_en         (i_tse_mac_mac_mii_connection_mii_tx_en),        //  output,   width = 1,                              .mii_tx_en
		.m_tx_err        (i_tse_mac_mac_mii_connection_mii_tx_err),       //  output,   width = 1,                              .mii_tx_err
		.m_rx_crs        (i_tse_pcs_0_mii_connection_mii_crs),            //   input,   width = 1,                              .mii_crs
		.m_rx_col        (i_tse_pcs_0_mii_connection_mii_col),            //   input,   width = 1,                              .mii_col
		.set_10          (i_tse_pcs_0_sgmii_status_connection_set_10),    //   input,   width = 1,         mac_status_connection.set_10
		.set_1000        (i_tse_pcs_0_sgmii_status_connection_set_1000),  //   input,   width = 1,                              .set_1000
		.rx_clkena       (i_tse_pcs_0_clock_enable_connection_rx_clkena), //   input,   width = 1,         mac_clkena_connection.rx_clkena
		.tx_clkena       (i_tse_pcs_0_clock_enable_connection_tx_clkena), //   input,   width = 1,                              .tx_clkena
		.tx_clk          (i_tse_pcs_0_pcs_transmit_clock_connection_clk), //   input,   width = 1,   pcs_mac_tx_clock_connection.clk
		.rx_clk          (i_tse_pcs_0_pcs_receive_clock_connection_clk),  //   input,   width = 1,   pcs_mac_rx_clock_connection.clk
		.magic_sleep_n   (1'b1),                                          // (terminated),                                            
		.magic_wakeup    (),                                              // (terminated),                                            
		.mac_eccstatus   (),                                              // (terminated),                                            
		.mdc             (),                                              // (terminated),                                            
		.mdio_in         (1'b0),                                          // (terminated),                                            
		.mdio_out        (),                                              // (terminated),                                            
		.mdio_oen        (),                                              // (terminated),                                            
		.rgmii_out1_aclr (),                                              // (terminated),                                            
		.rgmii_out1_din  (),                                              // (terminated),                                            
		.rgmii_in1_dout  (2'b00),                                         // (terminated),                                            
		.rgmii_in1_ck    (),                                              // (terminated),                                            
		.rgmii_out4_din  (),                                              // (terminated),                                            
		.rgmii_out4_ck   (),                                              // (terminated),                                            
		.rgmii_in1_pad   (),                                              // (terminated),                                            
		.rgmii_out4_aclr (),                                              // (terminated),                                            
		.rgmii_out1_pad  (1'b0),                                          // (terminated),                                            
		.rgmii_out1_ck   (),                                              // (terminated),                                            
		.rgmii_in4_dout  (8'b00000000),                                   // (terminated),                                            
		.rgmii_in4_pad   (),                                              // (terminated),                                            
		.rgmii_out4_pad  (4'b0000),                                       // (terminated),                                            
		.rgmii_in4_ck    (),                                              // (terminated),                                            
		.rgmii_in        (4'b0000),                                       // (terminated),                                            
		.rgmii_out       (),                                              // (terminated),                                            
		.rx_control      (1'b0),                                          // (terminated),                                            
		.tx_control      (),                                              // (terminated),                                            
		.eth_mode        (),                                              // (terminated),                                            
		.ena_10          ()                                               // (terminated),                                            
	);

	altera_eth_tse_avalon_arbiter #(
		.MAX_CHANNELS     (1),
		.MAC_ONLY         (0),
		.SLAVE_ADDR_WIDTH (8)
	) avalon_arbiter (
		.clk                (clk),                                        //   input,   width = 1,             clk.clk
		.reset              (reset),                                      //   input,   width = 1,           reset.reset
		.reg_data_out       (reg_data_out),                               //  output,  width = 32,        av_slave.readdata
		.reg_rd             (reg_rd),                                     //   input,   width = 1,                .read
		.reg_data_in        (reg_data_in),                                //   input,  width = 32,                .writedata
		.reg_wr             (reg_wr),                                     //   input,   width = 1,                .write
		.reg_busy           (reg_busy),                                   //  output,   width = 1,                .waitrequest
		.reg_addr           (reg_addr),                                   //   input,   width = 8,                .address
		.mac_address_0      (avalon_arbiter_av_mac_master_0_address),     //  output,   width = 8, av_mac_master_0.address
		.mac_readdata_0     (avalon_arbiter_av_mac_master_0_readdata),    //   input,  width = 32,                .readdata
		.mac_read_0         (avalon_arbiter_av_mac_master_0_read),        //  output,   width = 1,                .read
		.mac_writedata_0    (avalon_arbiter_av_mac_master_0_writedata),   //  output,  width = 32,                .writedata
		.mac_write_0        (avalon_arbiter_av_mac_master_0_write),       //  output,   width = 1,                .write
		.mac_waitrequest_0  (avalon_arbiter_av_mac_master_0_waitrequest), //   input,   width = 1,                .waitrequest
		.pcs_address_0      (avalon_arbiter_av_pcs_master_0_address),     //  output,   width = 5, av_pcs_master_0.address
		.pcs_readdata_0     (avalon_arbiter_av_pcs_master_0_readdata),    //   input,  width = 16,                .readdata
		.pcs_read_0         (avalon_arbiter_av_pcs_master_0_read),        //  output,   width = 1,                .read
		.pcs_writedata_0    (avalon_arbiter_av_pcs_master_0_writedata),   //  output,  width = 16,                .writedata
		.pcs_write_0        (avalon_arbiter_av_pcs_master_0_write),       //  output,   width = 1,                .write
		.pcs_waitrequest_0  (avalon_arbiter_av_pcs_master_0_waitrequest), //   input,   width = 1,                .waitrequest
		.mac_address_1      (),                                           // (terminated),                              
		.mac_readdata_1     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_1         (),                                           // (terminated),                              
		.mac_writedata_1    (),                                           // (terminated),                              
		.mac_write_1        (),                                           // (terminated),                              
		.mac_waitrequest_1  (1'b0),                                       // (terminated),                              
		.pcs_address_1      (),                                           // (terminated),                              
		.pcs_readdata_1     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_1         (),                                           // (terminated),                              
		.pcs_writedata_1    (),                                           // (terminated),                              
		.pcs_write_1        (),                                           // (terminated),                              
		.pcs_waitrequest_1  (1'b0),                                       // (terminated),                              
		.mac_address_2      (),                                           // (terminated),                              
		.mac_readdata_2     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_2         (),                                           // (terminated),                              
		.mac_writedata_2    (),                                           // (terminated),                              
		.mac_write_2        (),                                           // (terminated),                              
		.mac_waitrequest_2  (1'b0),                                       // (terminated),                              
		.pcs_address_2      (),                                           // (terminated),                              
		.pcs_readdata_2     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_2         (),                                           // (terminated),                              
		.pcs_writedata_2    (),                                           // (terminated),                              
		.pcs_write_2        (),                                           // (terminated),                              
		.pcs_waitrequest_2  (1'b0),                                       // (terminated),                              
		.mac_address_3      (),                                           // (terminated),                              
		.mac_readdata_3     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_3         (),                                           // (terminated),                              
		.mac_writedata_3    (),                                           // (terminated),                              
		.mac_write_3        (),                                           // (terminated),                              
		.mac_waitrequest_3  (1'b0),                                       // (terminated),                              
		.pcs_address_3      (),                                           // (terminated),                              
		.pcs_readdata_3     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_3         (),                                           // (terminated),                              
		.pcs_writedata_3    (),                                           // (terminated),                              
		.pcs_write_3        (),                                           // (terminated),                              
		.pcs_waitrequest_3  (1'b0),                                       // (terminated),                              
		.mac_address_4      (),                                           // (terminated),                              
		.mac_readdata_4     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_4         (),                                           // (terminated),                              
		.mac_writedata_4    (),                                           // (terminated),                              
		.mac_write_4        (),                                           // (terminated),                              
		.mac_waitrequest_4  (1'b0),                                       // (terminated),                              
		.pcs_address_4      (),                                           // (terminated),                              
		.pcs_readdata_4     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_4         (),                                           // (terminated),                              
		.pcs_writedata_4    (),                                           // (terminated),                              
		.pcs_write_4        (),                                           // (terminated),                              
		.pcs_waitrequest_4  (1'b0),                                       // (terminated),                              
		.mac_address_5      (),                                           // (terminated),                              
		.mac_readdata_5     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_5         (),                                           // (terminated),                              
		.mac_writedata_5    (),                                           // (terminated),                              
		.mac_write_5        (),                                           // (terminated),                              
		.mac_waitrequest_5  (1'b0),                                       // (terminated),                              
		.pcs_address_5      (),                                           // (terminated),                              
		.pcs_readdata_5     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_5         (),                                           // (terminated),                              
		.pcs_writedata_5    (),                                           // (terminated),                              
		.pcs_write_5        (),                                           // (terminated),                              
		.pcs_waitrequest_5  (1'b0),                                       // (terminated),                              
		.mac_address_6      (),                                           // (terminated),                              
		.mac_readdata_6     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_6         (),                                           // (terminated),                              
		.mac_writedata_6    (),                                           // (terminated),                              
		.mac_write_6        (),                                           // (terminated),                              
		.mac_waitrequest_6  (1'b0),                                       // (terminated),                              
		.pcs_address_6      (),                                           // (terminated),                              
		.pcs_readdata_6     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_6         (),                                           // (terminated),                              
		.pcs_writedata_6    (),                                           // (terminated),                              
		.pcs_write_6        (),                                           // (terminated),                              
		.pcs_waitrequest_6  (1'b0),                                       // (terminated),                              
		.mac_address_7      (),                                           // (terminated),                              
		.mac_readdata_7     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_7         (),                                           // (terminated),                              
		.mac_writedata_7    (),                                           // (terminated),                              
		.mac_write_7        (),                                           // (terminated),                              
		.mac_waitrequest_7  (1'b0),                                       // (terminated),                              
		.pcs_address_7      (),                                           // (terminated),                              
		.pcs_readdata_7     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_7         (),                                           // (terminated),                              
		.pcs_writedata_7    (),                                           // (terminated),                              
		.pcs_write_7        (),                                           // (terminated),                              
		.pcs_waitrequest_7  (1'b0),                                       // (terminated),                              
		.mac_address_8      (),                                           // (terminated),                              
		.mac_readdata_8     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_8         (),                                           // (terminated),                              
		.mac_writedata_8    (),                                           // (terminated),                              
		.mac_write_8        (),                                           // (terminated),                              
		.mac_waitrequest_8  (1'b0),                                       // (terminated),                              
		.pcs_address_8      (),                                           // (terminated),                              
		.pcs_readdata_8     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_8         (),                                           // (terminated),                              
		.pcs_writedata_8    (),                                           // (terminated),                              
		.pcs_write_8        (),                                           // (terminated),                              
		.pcs_waitrequest_8  (1'b0),                                       // (terminated),                              
		.mac_address_9      (),                                           // (terminated),                              
		.mac_readdata_9     (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_9         (),                                           // (terminated),                              
		.mac_writedata_9    (),                                           // (terminated),                              
		.mac_write_9        (),                                           // (terminated),                              
		.mac_waitrequest_9  (1'b0),                                       // (terminated),                              
		.pcs_address_9      (),                                           // (terminated),                              
		.pcs_readdata_9     (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_9         (),                                           // (terminated),                              
		.pcs_writedata_9    (),                                           // (terminated),                              
		.pcs_write_9        (),                                           // (terminated),                              
		.pcs_waitrequest_9  (1'b0),                                       // (terminated),                              
		.mac_address_10     (),                                           // (terminated),                              
		.mac_readdata_10    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_10        (),                                           // (terminated),                              
		.mac_writedata_10   (),                                           // (terminated),                              
		.mac_write_10       (),                                           // (terminated),                              
		.mac_waitrequest_10 (1'b0),                                       // (terminated),                              
		.pcs_address_10     (),                                           // (terminated),                              
		.pcs_readdata_10    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_10        (),                                           // (terminated),                              
		.pcs_writedata_10   (),                                           // (terminated),                              
		.pcs_write_10       (),                                           // (terminated),                              
		.pcs_waitrequest_10 (1'b0),                                       // (terminated),                              
		.mac_address_11     (),                                           // (terminated),                              
		.mac_readdata_11    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_11        (),                                           // (terminated),                              
		.mac_writedata_11   (),                                           // (terminated),                              
		.mac_write_11       (),                                           // (terminated),                              
		.mac_waitrequest_11 (1'b0),                                       // (terminated),                              
		.pcs_address_11     (),                                           // (terminated),                              
		.pcs_readdata_11    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_11        (),                                           // (terminated),                              
		.pcs_writedata_11   (),                                           // (terminated),                              
		.pcs_write_11       (),                                           // (terminated),                              
		.pcs_waitrequest_11 (1'b0),                                       // (terminated),                              
		.mac_address_12     (),                                           // (terminated),                              
		.mac_readdata_12    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_12        (),                                           // (terminated),                              
		.mac_writedata_12   (),                                           // (terminated),                              
		.mac_write_12       (),                                           // (terminated),                              
		.mac_waitrequest_12 (1'b0),                                       // (terminated),                              
		.pcs_address_12     (),                                           // (terminated),                              
		.pcs_readdata_12    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_12        (),                                           // (terminated),                              
		.pcs_writedata_12   (),                                           // (terminated),                              
		.pcs_write_12       (),                                           // (terminated),                              
		.pcs_waitrequest_12 (1'b0),                                       // (terminated),                              
		.mac_address_13     (),                                           // (terminated),                              
		.mac_readdata_13    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_13        (),                                           // (terminated),                              
		.mac_writedata_13   (),                                           // (terminated),                              
		.mac_write_13       (),                                           // (terminated),                              
		.mac_waitrequest_13 (1'b0),                                       // (terminated),                              
		.pcs_address_13     (),                                           // (terminated),                              
		.pcs_readdata_13    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_13        (),                                           // (terminated),                              
		.pcs_writedata_13   (),                                           // (terminated),                              
		.pcs_write_13       (),                                           // (terminated),                              
		.pcs_waitrequest_13 (1'b0),                                       // (terminated),                              
		.mac_address_14     (),                                           // (terminated),                              
		.mac_readdata_14    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_14        (),                                           // (terminated),                              
		.mac_writedata_14   (),                                           // (terminated),                              
		.mac_write_14       (),                                           // (terminated),                              
		.mac_waitrequest_14 (1'b0),                                       // (terminated),                              
		.pcs_address_14     (),                                           // (terminated),                              
		.pcs_readdata_14    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_14        (),                                           // (terminated),                              
		.pcs_writedata_14   (),                                           // (terminated),                              
		.pcs_write_14       (),                                           // (terminated),                              
		.pcs_waitrequest_14 (1'b0),                                       // (terminated),                              
		.mac_address_15     (),                                           // (terminated),                              
		.mac_readdata_15    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_15        (),                                           // (terminated),                              
		.mac_writedata_15   (),                                           // (terminated),                              
		.mac_write_15       (),                                           // (terminated),                              
		.mac_waitrequest_15 (1'b0),                                       // (terminated),                              
		.pcs_address_15     (),                                           // (terminated),                              
		.pcs_readdata_15    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_15        (),                                           // (terminated),                              
		.pcs_writedata_15   (),                                           // (terminated),                              
		.pcs_write_15       (),                                           // (terminated),                              
		.pcs_waitrequest_15 (1'b0),                                       // (terminated),                              
		.mac_address_16     (),                                           // (terminated),                              
		.mac_readdata_16    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_16        (),                                           // (terminated),                              
		.mac_writedata_16   (),                                           // (terminated),                              
		.mac_write_16       (),                                           // (terminated),                              
		.mac_waitrequest_16 (1'b0),                                       // (terminated),                              
		.pcs_address_16     (),                                           // (terminated),                              
		.pcs_readdata_16    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_16        (),                                           // (terminated),                              
		.pcs_writedata_16   (),                                           // (terminated),                              
		.pcs_write_16       (),                                           // (terminated),                              
		.pcs_waitrequest_16 (1'b0),                                       // (terminated),                              
		.mac_address_17     (),                                           // (terminated),                              
		.mac_readdata_17    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_17        (),                                           // (terminated),                              
		.mac_writedata_17   (),                                           // (terminated),                              
		.mac_write_17       (),                                           // (terminated),                              
		.mac_waitrequest_17 (1'b0),                                       // (terminated),                              
		.pcs_address_17     (),                                           // (terminated),                              
		.pcs_readdata_17    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_17        (),                                           // (terminated),                              
		.pcs_writedata_17   (),                                           // (terminated),                              
		.pcs_write_17       (),                                           // (terminated),                              
		.pcs_waitrequest_17 (1'b0),                                       // (terminated),                              
		.mac_address_18     (),                                           // (terminated),                              
		.mac_readdata_18    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_18        (),                                           // (terminated),                              
		.mac_writedata_18   (),                                           // (terminated),                              
		.mac_write_18       (),                                           // (terminated),                              
		.mac_waitrequest_18 (1'b0),                                       // (terminated),                              
		.pcs_address_18     (),                                           // (terminated),                              
		.pcs_readdata_18    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_18        (),                                           // (terminated),                              
		.pcs_writedata_18   (),                                           // (terminated),                              
		.pcs_write_18       (),                                           // (terminated),                              
		.pcs_waitrequest_18 (1'b0),                                       // (terminated),                              
		.mac_address_19     (),                                           // (terminated),                              
		.mac_readdata_19    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_19        (),                                           // (terminated),                              
		.mac_writedata_19   (),                                           // (terminated),                              
		.mac_write_19       (),                                           // (terminated),                              
		.mac_waitrequest_19 (1'b0),                                       // (terminated),                              
		.pcs_address_19     (),                                           // (terminated),                              
		.pcs_readdata_19    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_19        (),                                           // (terminated),                              
		.pcs_writedata_19   (),                                           // (terminated),                              
		.pcs_write_19       (),                                           // (terminated),                              
		.pcs_waitrequest_19 (1'b0),                                       // (terminated),                              
		.mac_address_20     (),                                           // (terminated),                              
		.mac_readdata_20    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_20        (),                                           // (terminated),                              
		.mac_writedata_20   (),                                           // (terminated),                              
		.mac_write_20       (),                                           // (terminated),                              
		.mac_waitrequest_20 (1'b0),                                       // (terminated),                              
		.pcs_address_20     (),                                           // (terminated),                              
		.pcs_readdata_20    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_20        (),                                           // (terminated),                              
		.pcs_writedata_20   (),                                           // (terminated),                              
		.pcs_write_20       (),                                           // (terminated),                              
		.pcs_waitrequest_20 (1'b0),                                       // (terminated),                              
		.mac_address_21     (),                                           // (terminated),                              
		.mac_readdata_21    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_21        (),                                           // (terminated),                              
		.mac_writedata_21   (),                                           // (terminated),                              
		.mac_write_21       (),                                           // (terminated),                              
		.mac_waitrequest_21 (1'b0),                                       // (terminated),                              
		.pcs_address_21     (),                                           // (terminated),                              
		.pcs_readdata_21    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_21        (),                                           // (terminated),                              
		.pcs_writedata_21   (),                                           // (terminated),                              
		.pcs_write_21       (),                                           // (terminated),                              
		.pcs_waitrequest_21 (1'b0),                                       // (terminated),                              
		.mac_address_22     (),                                           // (terminated),                              
		.mac_readdata_22    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_22        (),                                           // (terminated),                              
		.mac_writedata_22   (),                                           // (terminated),                              
		.mac_write_22       (),                                           // (terminated),                              
		.mac_waitrequest_22 (1'b0),                                       // (terminated),                              
		.pcs_address_22     (),                                           // (terminated),                              
		.pcs_readdata_22    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_22        (),                                           // (terminated),                              
		.pcs_writedata_22   (),                                           // (terminated),                              
		.pcs_write_22       (),                                           // (terminated),                              
		.pcs_waitrequest_22 (1'b0),                                       // (terminated),                              
		.mac_address_23     (),                                           // (terminated),                              
		.mac_readdata_23    (32'b00000000000000000000000000000000),       // (terminated),                              
		.mac_read_23        (),                                           // (terminated),                              
		.mac_writedata_23   (),                                           // (terminated),                              
		.mac_write_23       (),                                           // (terminated),                              
		.mac_waitrequest_23 (1'b0),                                       // (terminated),                              
		.pcs_address_23     (),                                           // (terminated),                              
		.pcs_readdata_23    (16'b0000000000000000),                       // (terminated),                              
		.pcs_read_23        (),                                           // (terminated),                              
		.pcs_writedata_23   (),                                           // (terminated),                              
		.pcs_write_23       (),                                           // (terminated),                              
		.pcs_waitrequest_23 (1'b0)                                        // (terminated),                              
	);

	altera_eth_tse_pcs_pma_nf_lvds #(
		.ENABLE_TIMESTAMPING (0),
		.DEV_VERSION         (4867),
		.ENABLE_ECC          (0),
		.ENABLE_REV_LOOPBACK (0),
		.DEVICE_FAMILY       ("ARRIA10"),
		.SYNCHRONIZER_DEPTH  (3),
		.ENABLE_CLK_SHARING  (0),
		.ENABLE_SGMII        (1),
		.PHY_IDENTIFIER      (0)
	) i_tse_pcs_0 (
		.clk                    (clk),                                                                   //   input,   width = 1, control_port_clock_connection.clk
		.reset                  (reset),                                                                 //   input,   width = 1,              reset_connection.reset
		.reg_addr               (avalon_arbiter_av_pcs_master_0_address),                                //   input,   width = 5,                  control_port.address
		.reg_data_out           (avalon_arbiter_av_pcs_master_0_readdata),                               //  output,  width = 16,                              .readdata
		.reg_rd                 (avalon_arbiter_av_pcs_master_0_read),                                   //   input,   width = 1,                              .read
		.reg_data_in            (avalon_arbiter_av_pcs_master_0_writedata),                              //   input,  width = 16,                              .writedata
		.reg_wr                 (avalon_arbiter_av_pcs_master_0_write),                                  //   input,   width = 1,                              .write
		.reg_busy               (avalon_arbiter_av_pcs_master_0_waitrequest),                            //  output,   width = 1,                              .waitrequest
		.ref_clk                (ref_clk),                                                               //   input,   width = 1,  pcs_ref_clk_clock_connection.clk
		.tx_clkena              (i_tse_pcs_0_clock_enable_connection_tx_clkena),                         //  output,   width = 1,       clock_enable_connection.tx_clkena
		.rx_clkena              (i_tse_pcs_0_clock_enable_connection_rx_clkena),                         //  output,   width = 1,                              .rx_clkena
		.gmii_rx_dv             (i_tse_pcs_0_gmii_connection_gmii_rx_dv),                                //  output,   width = 1,               gmii_connection.gmii_rx_dv
		.gmii_rx_d              (i_tse_pcs_0_gmii_connection_gmii_rx_d),                                 //  output,   width = 8,                              .gmii_rx_d
		.gmii_rx_err            (i_tse_pcs_0_gmii_connection_gmii_rx_err),                               //  output,   width = 1,                              .gmii_rx_err
		.gmii_tx_en             (i_tse_mac_mac_gmii_connection_gmii_tx_en),                              //   input,   width = 1,                              .gmii_tx_en
		.gmii_tx_d              (i_tse_mac_mac_gmii_connection_gmii_tx_d),                               //   input,   width = 8,                              .gmii_tx_d
		.gmii_tx_err            (i_tse_mac_mac_gmii_connection_gmii_tx_err),                             //   input,   width = 1,                              .gmii_tx_err
		.mii_rx_dv              (i_tse_pcs_0_mii_connection_mii_rx_dv),                                  //  output,   width = 1,                mii_connection.mii_rx_dv
		.mii_rx_d               (i_tse_pcs_0_mii_connection_mii_rx_d),                                   //  output,   width = 4,                              .mii_rx_d
		.mii_rx_err             (i_tse_pcs_0_mii_connection_mii_rx_err),                                 //  output,   width = 1,                              .mii_rx_err
		.mii_tx_en              (i_tse_mac_mac_mii_connection_mii_tx_en),                                //   input,   width = 1,                              .mii_tx_en
		.mii_tx_d               (i_tse_mac_mac_mii_connection_mii_tx_d),                                 //   input,   width = 4,                              .mii_tx_d
		.mii_tx_err             (i_tse_mac_mac_mii_connection_mii_tx_err),                               //   input,   width = 1,                              .mii_tx_err
		.mii_col                (i_tse_pcs_0_mii_connection_mii_col),                                    //  output,   width = 1,                              .mii_col
		.mii_crs                (i_tse_pcs_0_mii_connection_mii_crs),                                    //  output,   width = 1,                              .mii_crs
		.set_10                 (i_tse_pcs_0_sgmii_status_connection_set_10),                            //  output,   width = 1,       sgmii_status_connection.set_10
		.set_1000               (i_tse_pcs_0_sgmii_status_connection_set_1000),                          //  output,   width = 1,                              .set_1000
		.tx_clk                 (i_tse_pcs_0_pcs_transmit_clock_connection_clk),                         //  output,   width = 1, pcs_transmit_clock_connection.clk
		.rx_clk                 (i_tse_pcs_0_pcs_receive_clock_connection_clk),                          //  output,   width = 1,  pcs_receive_clock_connection.clk
		.reset_tx_clk           (rst_controller_reset_out_reset),                                        //   input,   width = 1, pcs_transmit_reset_connection.reset
		.reset_rx_clk           (rst_controller_001_reset_out_reset),                                    //   input,   width = 1,  pcs_receive_reset_connection.reset
		.led_crs                (led_crs),                                                               //  output,   width = 1,         status_led_connection.export
		.led_link               (led_link),                                                              //  output,   width = 1,                              .export
		.led_panel_link         (led_panel_link),                                                        //  output,   width = 1,                              .export
		.led_col                (led_col),                                                               //  output,   width = 1,                              .export
		.led_an                 (led_an),                                                                //  output,   width = 1,                              .export
		.led_char_err           (led_char_err),                                                          //  output,   width = 1,                              .export
		.led_disp_err           (led_disp_err),                                                          //  output,   width = 1,                              .export
		.rx_recovclkout         (rx_recovclkout),                                                        //  output,   width = 1,     serdes_control_connection.export
		.rx_reset               (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //   input,   width = 1,                      rx_reset.rx_reset
		.rx_reset_sequence_done (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), //   input,   width = 1,        rx_reset_sequence_done.rx_reset_sequence_done
		.tbi_rx_clk             (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //   input,   width = 1,                    tbi_rx_clk.tbi_rx_clk
		.tx_reset               (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //   input,   width = 1,                      tx_reset.tx_reset
		.tbi_tx_d_muxed         (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //  output,  width = 10,                tbi_tx_d_muxed.tbi_tx_d_muxed
		.tbi_rx_d_lvds          (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //   input,  width = 10,                 tbi_rx_d_lvds.tbi_rx_d_lvds
		.set_100                (),                                                                      // (terminated),                                            
		.hd_ena                 (),                                                                      // (terminated),                                            
		.pcs_phase_measure_clk  (1'b0),                                                                  // (terminated),                                            
		.rx_latency_adj         (),                                                                      // (terminated),                                            
		.tx_latency_adj         (),                                                                      // (terminated),                                            
		.tx_ptp_alignment       (),                                                                      // (terminated),                                            
		.pcs_eccstatus          ()                                                                       // (terminated),                                            
	);

	altera_eth_tse_nf_lvds_terminator #(
		.NUM_CHANNELS       (1),
		.SYNCHRONIZER_DEPTH (3),
		.DEVICE_FAMILY      ("ARRIA10")
	) i_lvdsio_terminator_0 (
		.lvds_inclock              (ref_clk),                                                               //   input,   width = 1,             lvds_inclock.clk
		.reset                     (reset),                                                                 //   input,   width = 1,                 reset_in.reset
		.lvds_rx_inclock           (i_lvdsio_terminator_0_lvds_rx_inclock_export),                          //  output,   width = 1,          lvds_rx_inclock.export
		.pll_areset_duplex         (),                                                                      //  output,   width = 1,        pll_areset_duplex.export
		.pll_areset_rx             (i_lvdsio_terminator_0_pll_areset_rx_export),                            //  output,   width = 1,            pll_areset_rx.export
		.pll_locked_tx             (i_lvdsio_tx_0_pll_locked_export),                                       //   input,   width = 1,            pll_locked_tx.export
		.lvds_tx_inclock           (i_lvdsio_terminator_0_lvds_tx_inclock_export),                          //  output,   width = 1,          lvds_tx_inclock.export
		.rx_coreclock              (i_lvdsio_rx_0_rx_coreclock_export),                                     //   input,   width = 1,             rx_coreclock.export
		.pll_areset_tx             (i_lvdsio_terminator_0_pll_areset_tx_export),                            //  output,   width = 1,            pll_areset_tx.export
		.pll_locked_rx             (i_lvdsio_rx_0_pll_locked_export),                                       //   input,   width = 1,            pll_locked_rx.export
		.rx_dpa_reset              (i_lvdsio_terminator_0_rx_dpa_reset_export),                             //  output,   width = 1,             rx_dpa_reset.export
		.rx_in                     (i_lvdsio_terminator_0_rx_in_export),                                    //  output,   width = 1,                    rx_in.export
		.rx_out                    (i_lvdsio_rx_0_rx_out_export),                                           //   input,  width = 10,                   rx_out.export
		.tx_in                     (i_lvdsio_terminator_0_tx_in_export),                                    //  output,  width = 10,                    tx_in.export
		.rx_dpa_locked             (i_lvdsio_rx_0_rx_dpa_locked_export),                                    //   input,   width = 1,            rx_dpa_locked.export
		.rx_divfwdclk              (i_lvdsio_rx_0_rx_divfwdclk_export),                                     //   input,   width = 1,             rx_divfwdclk.export
		.tx_out                    (i_lvdsio_tx_0_tx_out_export),                                           //   input,   width = 1,                   tx_out.export
		.rxp_0                     (rxp),                                                                   //   input,   width = 1,      serial_connection_0.export
		.txp_0                     (txp),                                                                   //  output,   width = 1,                         .export
		.rx_reset_0                (i_lvdsio_terminator_0_rx_reset_0_rx_reset),                             //  output,   width = 1,               rx_reset_0.rx_reset
		.rx_reset_sequence_done_0  (i_lvdsio_terminator_0_rx_reset_sequence_done_0_rx_reset_sequence_done), //  output,   width = 1, rx_reset_sequence_done_0.rx_reset_sequence_done
		.tbi_rx_clk_0              (i_lvdsio_terminator_0_tbi_rx_clk_0_tbi_rx_clk),                         //  output,   width = 1,             tbi_rx_clk_0.tbi_rx_clk
		.tx_reset_0                (i_lvdsio_terminator_0_tx_reset_0_tx_reset),                             //  output,   width = 1,               tx_reset_0.tx_reset
		.tbi_rx_d_lvds_0           (i_lvdsio_terminator_0_tbi_rx_d_lvds_0_tbi_rx_d_lvds),                   //  output,  width = 10,          tbi_rx_d_lvds_0.tbi_rx_d_lvds
		.tbi_tx_d_muxed_0          (i_tse_pcs_0_tbi_tx_d_muxed_tbi_tx_d_muxed),                             //   input,  width = 10,         tbi_tx_d_muxed_0.tbi_tx_d_muxed
		.pll_locked_duplex         (1'b0),                                                                  // (terminated),                                       
		.rxp_1                     (1'b0),                                                                  // (terminated),                                       
		.txp_1                     (),                                                                      // (terminated),                                       
		.rx_reset_1                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_1  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_1              (),                                                                      // (terminated),                                       
		.tx_reset_1                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_1           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_1          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_2                     (1'b0),                                                                  // (terminated),                                       
		.txp_2                     (),                                                                      // (terminated),                                       
		.rx_reset_2                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_2  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_2              (),                                                                      // (terminated),                                       
		.tx_reset_2                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_2           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_2          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_3                     (1'b0),                                                                  // (terminated),                                       
		.txp_3                     (),                                                                      // (terminated),                                       
		.rx_reset_3                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_3  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_3              (),                                                                      // (terminated),                                       
		.tx_reset_3                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_3           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_3          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_4                     (1'b0),                                                                  // (terminated),                                       
		.txp_4                     (),                                                                      // (terminated),                                       
		.rx_reset_4                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_4  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_4              (),                                                                      // (terminated),                                       
		.tx_reset_4                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_4           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_4          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_5                     (1'b0),                                                                  // (terminated),                                       
		.txp_5                     (),                                                                      // (terminated),                                       
		.rx_reset_5                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_5  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_5              (),                                                                      // (terminated),                                       
		.tx_reset_5                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_5           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_5          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_6                     (1'b0),                                                                  // (terminated),                                       
		.txp_6                     (),                                                                      // (terminated),                                       
		.rx_reset_6                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_6  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_6              (),                                                                      // (terminated),                                       
		.tx_reset_6                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_6           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_6          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_7                     (1'b0),                                                                  // (terminated),                                       
		.txp_7                     (),                                                                      // (terminated),                                       
		.rx_reset_7                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_7  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_7              (),                                                                      // (terminated),                                       
		.tx_reset_7                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_7           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_7          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_8                     (1'b0),                                                                  // (terminated),                                       
		.txp_8                     (),                                                                      // (terminated),                                       
		.rx_reset_8                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_8  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_8              (),                                                                      // (terminated),                                       
		.tx_reset_8                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_8           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_8          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_9                     (1'b0),                                                                  // (terminated),                                       
		.txp_9                     (),                                                                      // (terminated),                                       
		.rx_reset_9                (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_9  (),                                                                      // (terminated),                                       
		.tbi_rx_clk_9              (),                                                                      // (terminated),                                       
		.tx_reset_9                (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_9           (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_9          (10'b0000000000),                                                        // (terminated),                                       
		.rxp_10                    (1'b0),                                                                  // (terminated),                                       
		.txp_10                    (),                                                                      // (terminated),                                       
		.rx_reset_10               (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_10 (),                                                                      // (terminated),                                       
		.tbi_rx_clk_10             (),                                                                      // (terminated),                                       
		.tx_reset_10               (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_10          (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_10         (10'b0000000000),                                                        // (terminated),                                       
		.rxp_11                    (1'b0),                                                                  // (terminated),                                       
		.txp_11                    (),                                                                      // (terminated),                                       
		.rx_reset_11               (),                                                                      // (terminated),                                       
		.rx_reset_sequence_done_11 (),                                                                      // (terminated),                                       
		.tbi_rx_clk_11             (),                                                                      // (terminated),                                       
		.tx_reset_11               (),                                                                      // (terminated),                                       
		.tbi_rx_d_lvds_11          (),                                                                      // (terminated),                                       
		.tbi_tx_d_muxed_11         (10'b0000000000)                                                         // (terminated),                                       
	);

	my_eth_eth_tse_0_altera_lvds_1930_ikiykci i_lvdsio_rx_0 (
		.rx_in         (i_lvdsio_terminator_0_rx_in_export),           //   input,   width = 1,         rx_in.export
		.rx_out        (i_lvdsio_rx_0_rx_out_export),                  //  output,  width = 10,        rx_out.export
		.rx_coreclock  (i_lvdsio_rx_0_rx_coreclock_export),            //  output,   width = 1,  rx_coreclock.export
		.inclock       (i_lvdsio_terminator_0_lvds_rx_inclock_export), //   input,   width = 1,       inclock.export
		.pll_areset    (i_lvdsio_terminator_0_pll_areset_rx_export),   //   input,   width = 1,    pll_areset.export
		.rx_dpa_locked (i_lvdsio_rx_0_rx_dpa_locked_export),           //  output,   width = 1, rx_dpa_locked.export
		.rx_dpa_reset  (i_lvdsio_terminator_0_rx_dpa_reset_export),    //   input,   width = 1,  rx_dpa_reset.export
		.rx_divfwdclk  (i_lvdsio_rx_0_rx_divfwdclk_export),            //  output,   width = 1,  rx_divfwdclk.export
		.pll_locked    (i_lvdsio_rx_0_pll_locked_export)               //  output,   width = 1,    pll_locked.export
	);

	my_eth_eth_tse_0_altera_lvds_1930_ti62qla i_lvdsio_tx_0 (
		.tx_in      (i_lvdsio_terminator_0_tx_in_export),           //   input,  width = 10,      tx_in.export
		.tx_out     (i_lvdsio_tx_0_tx_out_export),                  //  output,   width = 1,     tx_out.export
		.inclock    (i_lvdsio_terminator_0_lvds_tx_inclock_export), //   input,   width = 1,    inclock.export
		.pll_areset (i_lvdsio_terminator_0_pll_areset_tx_export),   //   input,   width = 1, pll_areset.export
		.pll_locked (i_lvdsio_tx_0_pll_locked_export)               //  output,   width = 1, pll_locked.export
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset),                                         //   input,  width = 1, reset_in0.reset
		.clk            (i_tse_pcs_0_pcs_transmit_clock_connection_clk), //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset),                //  output,  width = 1, reset_out.reset
		.reset_req      (),                                              // (terminated),                       
		.reset_req_in0  (1'b0),                                          // (terminated),                       
		.reset_in1      (1'b0),                                          // (terminated),                       
		.reset_req_in1  (1'b0),                                          // (terminated),                       
		.reset_in2      (1'b0),                                          // (terminated),                       
		.reset_req_in2  (1'b0),                                          // (terminated),                       
		.reset_in3      (1'b0),                                          // (terminated),                       
		.reset_req_in3  (1'b0),                                          // (terminated),                       
		.reset_in4      (1'b0),                                          // (terminated),                       
		.reset_req_in4  (1'b0),                                          // (terminated),                       
		.reset_in5      (1'b0),                                          // (terminated),                       
		.reset_req_in5  (1'b0),                                          // (terminated),                       
		.reset_in6      (1'b0),                                          // (terminated),                       
		.reset_req_in6  (1'b0),                                          // (terminated),                       
		.reset_in7      (1'b0),                                          // (terminated),                       
		.reset_req_in7  (1'b0),                                          // (terminated),                       
		.reset_in8      (1'b0),                                          // (terminated),                       
		.reset_req_in8  (1'b0),                                          // (terminated),                       
		.reset_in9      (1'b0),                                          // (terminated),                       
		.reset_req_in9  (1'b0),                                          // (terminated),                       
		.reset_in10     (1'b0),                                          // (terminated),                       
		.reset_req_in10 (1'b0),                                          // (terminated),                       
		.reset_in11     (1'b0),                                          // (terminated),                       
		.reset_req_in11 (1'b0),                                          // (terminated),                       
		.reset_in12     (1'b0),                                          // (terminated),                       
		.reset_req_in12 (1'b0),                                          // (terminated),                       
		.reset_in13     (1'b0),                                          // (terminated),                       
		.reset_req_in13 (1'b0),                                          // (terminated),                       
		.reset_in14     (1'b0),                                          // (terminated),                       
		.reset_req_in14 (1'b0),                                          // (terminated),                       
		.reset_in15     (1'b0),                                          // (terminated),                       
		.reset_req_in15 (1'b0)                                           // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (reset),                                        //   input,  width = 1, reset_in0.reset
		.clk            (i_tse_pcs_0_pcs_receive_clock_connection_clk), //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),           //  output,  width = 1, reset_out.reset
		.reset_req      (),                                             // (terminated),                       
		.reset_req_in0  (1'b0),                                         // (terminated),                       
		.reset_in1      (1'b0),                                         // (terminated),                       
		.reset_req_in1  (1'b0),                                         // (terminated),                       
		.reset_in2      (1'b0),                                         // (terminated),                       
		.reset_req_in2  (1'b0),                                         // (terminated),                       
		.reset_in3      (1'b0),                                         // (terminated),                       
		.reset_req_in3  (1'b0),                                         // (terminated),                       
		.reset_in4      (1'b0),                                         // (terminated),                       
		.reset_req_in4  (1'b0),                                         // (terminated),                       
		.reset_in5      (1'b0),                                         // (terminated),                       
		.reset_req_in5  (1'b0),                                         // (terminated),                       
		.reset_in6      (1'b0),                                         // (terminated),                       
		.reset_req_in6  (1'b0),                                         // (terminated),                       
		.reset_in7      (1'b0),                                         // (terminated),                       
		.reset_req_in7  (1'b0),                                         // (terminated),                       
		.reset_in8      (1'b0),                                         // (terminated),                       
		.reset_req_in8  (1'b0),                                         // (terminated),                       
		.reset_in9      (1'b0),                                         // (terminated),                       
		.reset_req_in9  (1'b0),                                         // (terminated),                       
		.reset_in10     (1'b0),                                         // (terminated),                       
		.reset_req_in10 (1'b0),                                         // (terminated),                       
		.reset_in11     (1'b0),                                         // (terminated),                       
		.reset_req_in11 (1'b0),                                         // (terminated),                       
		.reset_in12     (1'b0),                                         // (terminated),                       
		.reset_req_in12 (1'b0),                                         // (terminated),                       
		.reset_in13     (1'b0),                                         // (terminated),                       
		.reset_req_in13 (1'b0),                                         // (terminated),                       
		.reset_in14     (1'b0),                                         // (terminated),                       
		.reset_req_in14 (1'b0),                                         // (terminated),                       
		.reset_in15     (1'b0),                                         // (terminated),                       
		.reset_req_in15 (1'b0)                                          // (terminated),                       
	);

endmodule
